#SPRING PROPERTIES
spring:
  kafka:
    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.trusted.packages: '*'
        partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    shutdown.enabled: true
endpoints:
  shutdown.enabled: true
