services:
  postgresql:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: xkiteDB
      PGDATA: /data/postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    container_name: postgresql
  jupyter:
    image: jupyterhub/jupyterhub
    ports:
      - '8000:8000'
    container_name: jupyterhub
  prometheus:
    image: prom/prometheus
    ports:
      - '9099:9090'
    volumes:
      - >-
        /Users/markkrasner/xkite/src/common/kite/download/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
  grafana:
    image: grafana/grafana-oss
    ports:
      - '3050:3000'
    environment:
      GF_PATHS_DATA: /var/lib/grafana
      GF_SECURITY_ALLOW_EMBEDDING: 'true'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_SMTP_ENABLED: 'true'
      GF_SECURITY_ADMIN_PASSWORD: xkite
    volumes:
      - provisioning:/etc/grafana/provisioning
      - dashboards:/var/lib/grafana/dashboards
    container_name: grafana
    depends_on:
      - prometheus
  zookeeper1:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 12182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:13888:12888;zookeeper2:23888:22888
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - '12182:2182'
    container_name: zookeeper1
  zookeeper2:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 22182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:13888:12888;zookeeper2:23888:22888
      ZOOKEEPER_SERVER_ID: 2
    ports:
      - '22182:2182'
    container_name: zookeeper2
  jmx-kafka1:
    image: bitnami/jmx-exporter:latest
    environment:
      SERVICE_PORT: 5556
    ports:
      - '5557:5556'
    volumes:
      - >-
        /Users/markkrasner/xkite/src/common/kite/download/jmx/jmxConfigKafka1.yml:/etc/myconfig.yml
    container_name: jmx-kafka1
    depends_on:
      - kafka1
    command:
      - '5556'
      - /etc/myconfig.yml
  kafka1:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:12182,zookeeper2:22182
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: METRICS:PLAINTEXT,INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper1:12182,zookeeper2:22182
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      KAFKA_HEAP_OPTS: '-Xmx512M -Xms512M'
      KAFKA_BROKER_ID: 101
      KAFKA_JMX_PORT: 9991
      KAFKA_LISTENERS: METRICS://:29092,PLAINTEXT://:9092,INTERNAL://:9095
      KAFKA_ADVERTISED_LISTENERS: METRICS://kafka1:29092,PLAINTEXT://localhost:9092,INTERNAL://kafka1:9095
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka1:29092
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    ports:
      - '9092:9092'
    volumes: []
    container_name: kafka1
    depends_on:
      - postgresql
      - zookeeper1
      - zookeeper2
  jmx-kafka2:
    image: bitnami/jmx-exporter:latest
    environment:
      SERVICE_PORT: 5556
    ports:
      - '5558:5556'
    volumes:
      - >-
        /Users/markkrasner/xkite/src/common/kite/download/jmx/jmxConfigKafka2.yml:/etc/myconfig.yml
    container_name: jmx-kafka2
    depends_on:
      - kafka2
    command:
      - '5556'
      - /etc/myconfig.yml
  kafka2:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:12182,zookeeper2:22182
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: METRICS:PLAINTEXT,INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper1:12182,zookeeper2:22182
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      KAFKA_HEAP_OPTS: '-Xmx512M -Xms512M'
      KAFKA_BROKER_ID: 102
      KAFKA_JMX_PORT: 9992
      KAFKA_LISTENERS: METRICS://:29092,PLAINTEXT://:9093,INTERNAL://:9095
      KAFKA_ADVERTISED_LISTENERS: METRICS://kafka2:29092,PLAINTEXT://localhost:9093,INTERNAL://kafka2:9095
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka2:29092
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    ports:
      - '9093:9092'
    volumes: []
    container_name: kafka2
    depends_on:
      - postgresql
      - zookeeper1
      - zookeeper2
  spring:
    image: eclipse-temurin
    ports:
      - '8080:8080'
    environment:
      JAVA_OPTS: ''
      SPRING_CONFIG_LOCATION: /etc/myconfig.yml
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka1:9095,kafka2:9095
      SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS: kafka1:9095,kafka2:9095
      SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS: kafka1:9095,kafka2:9095
    command: java -jar /app.jar
    volumes:
      - >-
        /Users/markkrasner/xkite/src/common/kite/download/spring/app.jar:/app.jar
      - >-
        /Users/markkrasner/xkite/src/common/kite/download/spring/application.yml:/etc/myconfig.yml
    container_name: spring
    depends_on:
      - kafka1
      - kafka2
volumes:
  dashboards:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/markkrasner/xkite/src/common/kite/download/grafana/dashboards
  provisioning:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/markkrasner/xkite/src/common/kite/download/grafana/provisioning
  postgresql:
    driver: local
