global:
  scrape_interval: 5s
  evaluation_interval: 2s
  scrape_timeout: 4s
rule_files:
  - null
scrape_configs:
  - job_name: xkite
    static_configs:
      - targets:
          - jmx-kafka1:5556
          - jmx-kafka2:5556
