import Head from 'next/head';

export default function Display() {
  return (
    <>
      <Head>
        <title>Dummy Display Page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css2?family=Inter:wght@100&display=swap'
        />
      </Head>
      <main>
        <h1>Just a dummy display Page</h1>
      </main>
    </>
  );
}
